                                                            26th Feb Assignment

Q1.Ans

In [1]:
import numpy as np

list_=['1','2','3','4','5']

array_list = np.array(object=list_)

# Yeah, both are different 

arr=type(array_list)
lst=type(list_)

print("Data type of array_list is ",arr)

print("Data type of list_ is ",lst)

Data type of array_list is  <class 'numpy.ndarray'>
Data type of list_ is  <class 'list'>


Q2.Ans

In [2]:
import pandas as pd

df =pd.DataFrame({"List":list_}) # creating dataframe of list_ 
df1=pd.DataFrame(array_list)     # creating dataframe of array_list

lst_elements = df.dtypes   # finding datatypes of each element in a list

arr_elements = df1.dtypes   # finding datatypes of each element in a array


print("Data type of each and every elements in  list_ is ",lst_elements)
print("Data type of each and every elements in  array_list is ",arr_elements)



Data type of each and every elements in  list_ is  List    object
dtype: object
Data type of each and every elements in  array_list is  0    object
dtype: object


Q3.Ans

In [3]:
# yeah both will be different

array_list1 = np.array(object=list_ , dtype = int)


df2=pd.DataFrame(array_list1)

lst_elements1 = df.dtypes   # finding datatypes of each element in a list

arr_elements1 = df2.dtypes   # finding datatypes of each element in a array


print("Data type of each and every elements in  list_ is ",lst_elements1)
print("Data type of each and every elements in  array_list is ",arr_elements1)

Data type of each and every elements in  list_ is  List    object
dtype: object
Data type of each and every elements in  array_list is  0    int64
dtype: object


Q4.Ans

In [4]:
import numpy as np

num_list=[[1,2,3],[4,5,6]]

num_array=np.array(object=num_list)

In [5]:
#Q4(i)

num_array.shape

(2, 3)

In [6]:
#Q4(ii)

num_array.size

6

Q5.Ans

In [7]:
mat_3by3= np.zeros((3,3))

print(mat_3by3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6.Ans


In [8]:
mat_1=np.identity(5)

print(mat_1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
